### ISSUE TITLE
oneplus3t@lineageOS 14.1&magisk14.0 无法更新hosts文件

### ISSUE THREAD

**Issue by edisonyan** [mcxinyu/HouSi#2]
一加3t
系统：lineageOS 14.1
root：magisk 14.0
问题：已成功获取root权限并赋予后司，点击更新hosts显示更新成功，但是点击查看hosts文件并未更新。

**Comment by mcxinyu** [comment]
@edisonyan 请尝试修改 hosts 源试试，不行的话我再找你手机测试下。

**Comment by edisonyan** [comment]
![screenshot_20171214-115455](https://user-images.githubusercontent.com/3954670/33984481-bc2a6542-e0f2-11e7-81a5-b1d05c0f5090.png)
![screenshot_20171214-115507](https://user-images.githubusercontent.com/3954670/33984483-bf0a662c-e0f2-11e7-8af6-9e5e84957334.png)
![screenshot_20171214-171731](https://user-images.githubusercontent.com/3954670/33984489-c29f5c0c-e0f2-11e7-81b3-c5ec1482e9a6.png)
更换过host源后依然无法成功更新

**Comment by mcxinyu** [comment]
挺麻烦，手头没有一加3t，我看看我的手机能不能刷lineageOS 14.1吧。等我...

**Comment by mcxinyu** [comment]
挺麻烦，手头没有一加3t，我看看我的手机能不能刷lineageOS 14.1吧。等我...

**Comment by lrinQVQ** [comment]
专门刷了一次LOS 14.1使用magisk 14.5测试版 无法复现 能够正常更新

**Comment by edisonyan** [comment]
刷回官方H2OS 可以正常更新hosts，应该是第三方ROM的原因，感谢作者带来这么好的app。

**Comment by mcxinyu** [comment]
暂时解决，是rom问题，后续有时间再排查。
