### ISSUE TITLE
安卓手机更新后一片空白

### ISSUE THREAD

**Issue by 123ysys** [mcxinyu/HouSi#3]
过一段时间就会空白，得重启手机更新才行。
![screenshot_2018-10-17-13-52-49-250_io github mcxinyu housi](https://user-images.githubusercontent.com/27964272/47121606-e0ef0e00-d2a5-11e8-9e65-5a439fe43a6e.png)

**Comment by mcxinyu** [comment]
是什么型号手机呢？

**Comment by lrinQVQ** [comment]
//似乎是MIUI 小米系列0.0

**Comment by 123ysys** [comment]
@IrinQVQ qvq可真是大神。
@mcxinyu 是的，是miui。

**Comment by mcxinyu** [comment]
我要不要加个重启手机功能呢？![image](https://user-images.githubusercontent.com/9566116/48000551-c12e6580-e140-11e8-83d1-5b9a617c5280.png)

**Comment by 123ysys** [comment]
@mcxinyu lol，这权限有点大了吧😂。
