### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by E7KMbb** [mcxinyu/HouSi#5]
可以加入hosts编辑功能这样就方便了许多

**Comment by mcxinyu** [comment]
有准备了，敬请期待。
有建议可以直接在这里讨论。

接下来可能会修改交互方式，如果大家对交互有建议可以提出来哦。

**Comment by mcxinyu** [comment]
@E7KMbb 编辑功能请参考 [release](https://github.com/mcxinyu/HouSi/releases/tag/v1.2.8)

**Comment by SerCom-KC** [comment]
我就懒得开新 issue 了
这个功能需要强制纯文本格式（）
粘贴带格式的文本会变成 HTML 代码

**Comment by mcxinyu** [comment]
> 我就懒得开新 issue 了
> 这个功能需要强制纯文本格式（）
> 粘贴带格式的文本会变成 HTML 代码
> 
> 以及建议添加搜索功能
> 
> 还有Copyright年份

是说粘贴为纯文本么？

**Comment by SerCom-KC** [comment]
@mcxinyu
是的，改成只接受纯文本粘贴（目前的 app 是支持带格式文本粘贴的）。

**Comment by mcxinyu** [comment]
我看看先吧
